services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - static_volume:/app/staticfiles # Share static files with Nginx
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings_production

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - web
        volumes:
            - static_volume:/static:ro # Read-only mount for Nginx
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
